[package]
name = "robotica-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.33", optional = true, features = ["serde"] }
serde = { version = "1.0.196", features = ["derive", "rc"] }
thiserror = "1.0.57"
serde_json = "1.0.111"
tracing = "0.1.35"
bytes = "1.1.0"
prost = { version = "0.12.3", optional = true }
prost-types = { version = "0.12.3", optional = true }

[build-dependencies]
prost-build = { version = "0.12.3", optional = true }

[dev-dependencies]
approx = "0.5.1"
chrono-tz = "0.8.5"

[features]
chrono = ["dep:chrono"]
websockets = ["dep:prost", "dep:prost-types", "dep:prost-build"]
