[package]
name = "robotica-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.22", optional = true }
serde = { version = "1.0.147", features = ["derive"] }
thiserror = "1.0.30"
serde_json = "1.0.73"
tracing = "0.1.35"
bytes = "1.1.0"
prost = "0.11.5"
prost-types = "0.11.5"

[build-dependencies]
prost-build = { version = "0.11.5" }

[dev-dependencies]
chrono-tz = "0.8.1"

[features]
chrono = ["dep:chrono"]
