[package]
name = "robotica-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", optional = true, features = ["serde"] }
serde = { version = "1.0.158", features = ["derive"] }
thiserror = "1.0.40"
serde_json = "1.0.94"
tracing = "0.1.35"
bytes = "1.1.0"
prost = { version = "0.12.0", optional = true }
prost-types = { version = "0.12.0", optional = true }

[build-dependencies]
prost-build = { version = "0.12.0", optional = true }

[dev-dependencies]
chrono-tz = "0.8.1"

[features]
chrono = ["dep:chrono"]
websockets = ["dep:prost", "dep:prost-types", "dep:prost-build"]
