#!/bin/sh
set -ex

cd src/display/images

do_image() {
    image="$1"
    background="$2"
    inkscape -w 64 -h 64 "$image.svg" --export-type="png" -o - | pngtopnm -mix -background "$background" | ppmtopgm | ppmtotga -mono > "$image"_64x64.tga
}

do_images() {
    prefix="$1"
    do_image "$prefix"_off black
    do_image "$prefix"_hard_off black
    do_image "$prefix"_on white
    do_image "$prefix"_on_other black
}

do_images light
do_images fan
do_images wake_up
do_images tv
