[package]
name = "brian-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
tokio = { version = "1.21.1", features = ["full"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
anyhow = "1.0.66"
serde_path_to_error = "0.1.8"
chrono = "0.4.22"
chrono-tz = "0.8.0"
thiserror = "1.0.37"
color-backtrace = "0.5.1"
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
robotica-common = { path = "../robotica-common" }
robotica-backend = { path = "../robotica-backend" }
