[package]
name = "brian-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.111"
anyhow = "1.0.79"
serde_yaml = "0.9.30"
chrono = { version = "0.4.34", features = ["serde"] }
chrono-tz = "0.8.6"
thiserror = "1.0.57"
color-backtrace = "0.6.1"
tracing = "0.1.35"
tracing-subscriber = "0.3.18"
robotica-common = { path = "../robotica-common", features = ["websockets"] }
robotica-backend = { path = "../robotica-backend", features = ["websockets", "scheduler"] }
influxdb = { version = "0.7.1", features = ["derive"]}
reqwest = { version = "0.11.24", features = ["json"] }
envconfig = "0.10.0"
tap = "1.0.1"

[dev-dependencies]
float-cmp = "0.9.0"
