[package]
name = "brian-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.2", features = ["full"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
anyhow = "1.0.66"
serde_path_to_error = "0.1.8"
chrono = { version = "0.4.22", features = ["serde"] }
chrono-tz = "0.8.0"
thiserror = "1.0.37"
color-backtrace = "0.5.1"
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
robotica-common = { path = "../robotica-common", features = ["websockets"] }
robotica-backend = { path = "../robotica-backend", features = ["websockets"] }
influxdb = { features = [
    "derive",
], git = "https://github.com/influxdb-rs/influxdb-rust.git" }
reqwest = { version = "0.11.6", features = ["json"] }

[dev-dependencies]
float-cmp = "0.9.0"
